### ISSUE TITLE
push to Docker Hub

### ISSUE THREAD

**Issue by balhoff** [phenoscape/pipeline-tools#2]
@hlapp can you please add me and @Shalsh23 to the Phenoscape Docker org so that we can publish this forthcoming docker container there?

@Shalsh23 when you have access, please add a script to this repo demonstrating the required operations for tagging a new build of the container and pushing to Docker Hub.

**Comment by hlapp** [comment]
I need your Docker IDs for that.

**Comment by hlapp** [comment]
Also, you might be aware that GitHub Packages supports Docker images too? See [GitHub Packages](https://help.github.com/en/packages/publishing-and-managing-packages/about-github-packages) and [configuring Docker to use with Github](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages). Also, there are GitHub Actions. E.e., [example for using GitHub Actions to build a Docker image](https://www.prestonlamb.com/blog/creating-a-docker-image-with-github-actions).

**Comment by balhoff** [comment]
Mine is balhoff. Thanks, I didn't know about github packages for that.

**Comment by hlapp** [comment]
> @hlapp can you please add me and @Shalsh23 to the Phenoscape Docker org so that we can publish this forthcoming docker container there?

Done.

**Comment by Shalsh23** [comment]
@balhoff @hlapp I still don't have the rights to publish the docker image in the `phenoscape/pipeline-tools` repository. I am getting `denied: requested access to the resource is denied` error.

**Comment by balhoff** [comment]
I checked the settings and this should work in theory. Are you using username `shalsh`?

**Comment by Shalsh23** [comment]
> I checked the settings and this should work in theory. Are you using username `shalsh`?

Yes.

**Comment by balhoff** [comment]
Please try again, I tried increasing privileges.

**Comment by hlapp** [comment]
It seems very unlikely that the privileges were insufficient. It explicitly included `write` which includes the permission to push to the repo.

@Shalsh23 did you authenticate to Docker Hub in the current Docker daemon session? You must first authenticate, or otherwise no write action will succeed.

**Comment by Shalsh23** [comment]
Yes, I did authenticate. But turns out, all I needed to do was restart my terminal. The images have been pushed now.
